#!/bin/bash

domain=$1

RED='\033[31m' 
GRN='\033[32m'
INF='\033[36m'
NC='\033[0m'


script_name="add_threat_ip"

if [ $# -eq 1 ]
then
        echo -e "$script_name: ${INF}INFO${NC}: Validating Domain Name."
else
        echo "$script_name: usage: sudo $script_name \"example.com\""
        echo "$script_name: usage: sudo $script_name \"label.example.com\""
        exit 1
fi


# Validate domain name
domain_regex="^([a-zA-Z0-9][a-zA-Z0-9-]{0,61}[a-zA-Z0-9]\.)+[a-zA-Z]{2,}$"

if [[ "$domain" =~ $domain_regex ]]; then
        echo -e "$script_name: ${INF}INFO${NC}: $domain is valid."
        echo -e "$script_name: ${INF}INFO${NC}: Checking if $domain is already in the block list."
        if /usr/sbin/get_threat_domain "$domain" > /dev/null 2>&1
        then
                echo -e "$script_name: ${INF}INFO${NC}: $domain is already in the block list."
                exit 0
        fi

        echo -e "$script_name: ${INF}INFO${NC}: $domain not found in the block list."
        echo -e "$script_name: ${INF}INFO${NC}: Blocking $domain"
        if echo $domain >> /path/to/baddomain.txt
        then
                echo -e "$script_name: ${GRN}SUCCESS${NC}: $domain blocked successfully."
                exit 0
        else
                echo -e "$script_name: ${RED}FAILED${NC}: Could not block $domain"
                exit 1
        fi
else
        echo -e "$script_name: ${RED}ERROR${NC}: $domain is not a valid domain address."
        echo
        echo "$script_name: usage: sudo $script_name \"example.com\""
        echo "$script_name: usage: sudo $script_name \"label.example.com\""
        exit 1
fi
